### ISSUE TITLE
Doesn't filter out input from a physical keyboard and crashes with java.text.ParseException: Unparseable number

### ISSUE THREAD

**Issue by Doctoror** [Muratthekus/Compose-CurrencyText#2]
Steps to reproduce:
In emulator, type any non-digit charater with a physical keyboard, like "a"

Expected behaviour:
non-digit character is ignored

Actual behaviour:
```
java.text.ParseException: Unparseable number: "a"
    at java.text.NumberFormat.parse(NumberFormat.java:423)
    at me.thekusch.composeview.ComposeViewKt.isLimitExceeded(ComposeView.kt:149)
    at me.thekusch.composeview.ComposeViewKt.access$isLimitExceeded(ComposeView.kt:1)
    at me.thekusch.composeview.ComposeViewKt.CurrencyTextField-ygcbOzY(ComposeView.kt:85)
```

Even though it is pretty rare these days, but I believe Android devices may still have physical keyboards.

**Comment by Doctoror** [comment]
I have this fixed, I'll open a pull request later.
